CREATE TABLE cuentas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(64) NOT NULL,
    Clave VARCHAR(128) NOT NULL,
    Correo VARCHAR(200) NOT NULL,
    Ropa INT NOT NULL,
    X FLOAT NOT NULL DEFAULT 1767.0145,
    Y FLOAT NOT NULL DEFAULT -1896.5106,
    Z FLOAT NOT NULL DEFAULT 13.5634,
    Genero INT NOT NULL,
    Vida FLOAT NOT NULL DEFAULT 100,
    Dinero INT NOT NULL DEFAULT 0,
    Edad INT NOT NULL DEFAULT 0,
    Chaleco FLOAT NOT NULL DEFAULT 0.0,
    Admin INT NULL,
    Ban INT NULL
);